repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: .venv/bin/ruff check . --fix
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: ruff-format
        name: ruff format
        entry: .venv/bin/ruff format .
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: pytest
        name: pytest
        entry: .venv/bin/python -m pytest --cov=skeleton --cov-report=term-missing --cov-report=xml --cov-fail-under=75
        language: system
        pass_filenames: false
        stages: [pre-commit]
      - id: gitlint
        name: gitlint
        entry: .venv/bin/python -m gitlint.cli --msg-filename
        language: system
        stages: [commit-msg]
