"""Session manifest writing for IDE and automation integrations."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from skeleton_replay.version import __version__

JsonObject = dict[str, Any]


@dataclass(frozen=True)
class SessionTarget:
    """Target that one Skeleton session traced."""

    kind: str
    path: Path | None = None
    label: str | None = None
    args: tuple[str, ...] = ()

    def to_json(self) -> JsonObject:
        """Return a JSON-compatible target description."""
        payload: JsonObject = {"kind": self.kind, "args": list(self.args)}
        if self.path is not None:
            payload["path"] = str(self.path)
        if self.label is not None:
            payload["label"] = self.label
        return payload


@dataclass(frozen=True)
class SessionArtifactSet:
    """Paths generated by one Skeleton session."""

    trace_path: Path
    snapshot_path: Path
    workflow_path: Path
    quality_path: Path
    quality_markdown_path: Path
    report_path: Path | None
    session_path: Path

    def to_json(self) -> JsonObject:
        """Return JSON-compatible artifact paths."""
        payload: JsonObject = {
            "trace": str(self.trace_path),
            "snapshot": str(self.snapshot_path),
            "workflow": str(self.workflow_path),
            "quality": str(self.quality_path),
            "quality_markdown": str(self.quality_markdown_path),
            "session": str(self.session_path),
        }
        if self.report_path is not None:
            payload["report"] = str(self.report_path)
        return payload


@dataclass(frozen=True)
class SessionManifestWriter:
    """Writes a stable manifest for the artifact set produced by one session."""

    schema_version: int = 1

    def write(
        self,
        *,
        session_path: Path,
        command: str,
        invocation: tuple[str, ...],
        project_root: Path,
        target: SessionTarget,
        artifacts: SessionArtifactSet,
        event_count: int,
        node_count: int,
        edge_count: int,
        target_exit_code: int,
        target_error: str | None,
        report_opened: bool,
    ) -> None:
        """Write ``session.json`` for IDEs and automation tools."""
        session_path.parent.mkdir(parents=True, exist_ok=True)
        payload: JsonObject = {
            "schema_version": self.schema_version,
            "skeleton_version": __version__,
            "command": command,
            "invocation": list(invocation),
            "project_root": str(project_root),
            "target": target.to_json(),
            "artifacts": artifacts.to_json(),
            "metrics": {
                "events": event_count,
                "nodes": node_count,
                "edges": edge_count,
            },
            "target_exit_code": target_exit_code,
            "target_error": target_error,
            "report_opened": report_opened,
        }
        session_path.write_text(json.dumps(payload, indent=2, sort_keys=True), encoding="utf-8")
